// AUTO-GENERATED by @hono/inertia/vite. Do not edit.
import type app from '../../../server.js'

export type PageName = 'Dashboard' | 'Events/Index' | 'Login' | 'Permits/Index' | 'Permits/New' | 'Permits/Show' | 'Segments/Form' | 'Segments/Index' | 'Setup' | 'SpaceWeather/Index' | 'Users/Form' | 'Users/Index' | 'Workers/Form' | 'Workers/Index'

declare module '@hono/inertia' {
  interface InertiaPages {
    'Dashboard': unknown
    'Events/Index': unknown
    'Login': unknown
    'Permits/Index': unknown
    'Permits/New': unknown
    'Permits/Show': unknown
    'Segments/Form': unknown
    'Segments/Index': unknown
    'Setup': unknown
    'SpaceWeather/Index': unknown
    'Users/Form': unknown
    'Users/Index': unknown
    'Workers/Form': unknown
    'Workers/Index': unknown
  }
  interface AppRegistry {
    app: typeof app
  }
}

export type { PageProps } from '@hono/inertia'
